name: pigation
version: 1.0.29
description: An irrigation and out door lighting controller for the Raspbery PI.
repository: https://github.com/bsutton/IrrigationForPi
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  args: ^2.3.0
  dcli: ^1.0.0
  docker2: ^2.0.0
  github: ^8.1.1
  nginx_le_shared: ^7.0.2
  path: ^1.6.4
  settings_yaml: ^3.0.6
  uuid: ^3.0.4
  pub_release: ^7.1.14
  collection: ^1.15.0-nullsafety.4
dev_dependencies: 
  test: ^1.0.0
executables: 
  pig_build: 
  pig_install: 
  pig_reconfigure: 
  pig_start: 
  pig_stop: 

dependency_overrides:
  dcli:
    path: ../../dcli
