name: pigation
version: 1.0.29
description: An irrigation and out door lighting controller for the Raspbery PI.
repository: https://github.com/bsutton/IrrigationForPi
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  args: ^2.3.0
  collection: ^1.15.0-nullsafety.4
  dcli: ^1.16.0
  dcli_scripts: ^1.1.20
  docker2: ^2.0.0
  github: ^9.4.0
  nginx_le_shared: ^8.0.0
  path: ^1.6.4
  pub_release: ^9.0.0
  settings_yaml: ^4.0.0
  uuid: ^3.0.4
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.0.0
executables: 
  pig_build: 
  pig_install: 
  pig_reconfigure: 
  pig_start: 
  pig_stop: 


