name: pigation
version: 2.0.0
description: An irrigation and out door lighting controller for the Raspbery PI.
repository: https://github.com/bsutton/IrrigationForPi
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  archive: ^3.3.7
  args: ^2.3.0
  collection: ^1.17.0
  dcli: ^3.0.2
  dcli_scripts: ^3.0.0
  docker2: ^4.0.2
  github: ^9.4.0
  nginx_le_shared: ^9.0.4
  path: ^1.6.4
  pub_release: ^9.0.2
  settings_yaml: ^7.0.0
  uuid: ^3.0.4
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.0.0
executables: 
  pig_build: 
  pig_install: 
  pig_reconfigure: 
  pig_start: 
  pig_stop: 
