name: certbot
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snap for Lets Encrypt's certbot
description: | 
  Certbot allows you to create an install SSL Certificates supplied
  free of charge via the Lets Encrypt foundation.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
  

apps:
  certbot:
    command: certbot
    plugs: [network, network-bind]

parts: 
  certbot:
    plugin: python
    source: https://github.com/certbot/certbot.git
    source-type: git

